export enum FiltersList {
  litrpg = 'LitRPG',
  gamelit = 'Gamelit',
  progression = 'Progression',
  vr = 'VR',
  system = 'the System',
  humour = 'Humour',
  nonhumanmc = 'Non-human MC',
  completed = 'Completed',
  ongoing = 'Ongoing',
  femalemc = 'Female MC',
  isekai = 'Isekai',
  overpowered = 'Overpowered MC',
  mage = 'Mage',
  fighter = 'Fighter',
  rogue = 'Rogue',
  noncombat = 'Non-combat MC',
  guns = 'Guns',
}
